#!/bin/bash
# /usr/local/sbin/wmp
# This file is part of the WakeMyPotato (WMP) systemd service.
# https://github.com/pablogila/WakeMyPotato
# It will safely power off RAID disks before an emergency shutdown on AC outage.
# The system is automatically restored after timeout or once power is back.

version="v2.4.1"

if [ "$1" = "help" ]; then
    echo ""
    echo "WakeMyPotato user commands:"
    echo ""
    echo "sudo wmp help                    Show this help message"
    echo "sudo wmp version                 Print the software version"
    echo "sudo wmp status                  Check the service status"
    echo "sudo wmp log                     View warning logs"
    echo "sudo wmp set <seconds> [<IP>]    Set new configuration"
    echo "sudo wmp check <seconds> [<IP>]  Run a manual check now"
    echo "sudo wmp force <seconds>         Force a manual shutdown now"
    echo "sudo wmp stop                    Stop the service"
    echo "sudo wmp start                   Start the service"
    echo "sudo wmp uninstall               Uninstall the service"
    echo ""
    echo "Visit the project page for more info and updates:"
    echo "https://github.com/pablogila/WakeMyPotato"
    echo ""

elif [ "$1" = "version" ]; then
    echo "$version"

elif [ "$1" = "status" ]; then
    echo "WakeMyPotato status:"
    tail -n 1 /etc/systemd/system/wmp.service
    systemctl status wmp.timer

elif [ "$1" = "log" ]; then
    sudo journalctl -u wmp -p warning -r

elif [ "$1" = "set" ]; then
    SECONDS=$2
    IP=$3
    if [[ ! "$SECONDS" =~ ^[0-9]+$ ]]; then
        echo "Invalid input, please enter a positive integer! Aborting..." >&2
        exit 1
    fi
    SETTINGS="$SECONDS"
    if [ -n "$IP" ]; then
        SETTINGS="$SETTINGS $IP"
    fi
    sed -i "s|^ExecStart=.*|ExecStart=/usr/local/sbin/wmp-check $SETTINGS|" /etc/systemd/system/wmp.service
    systemctl daemon-reload
    echo "Configuration updated successfully!"

elif [ "$1" = "check" ]; then
    SECONDS=$2
    IP=$3
    if [[ ! "$SECONDS" =~ ^[0-9]+$ ]]; then
        echo "Invalid input, please enter a positive integer! Aborting..." >&2
        exit 1
    fi
    SETTINGS="$SECONDS"
    if [ -n "$IP" ]; then
        SETTINGS="$SETTINGS $IP"
    fi
    /usr/local/sbin/wmp-check "$SETTINGS"

elif [ "$1" = "force" ]; then
    if [[ ! "$2" =~ ^[0-9]+$ ]]; then
        echo "Invalid input, please enter a positive integer! Aborting..." >&2
        exit 1
    fi
    echo "User forced a manual shutdown" | systemd-cat -p 'warning' -t 'wmp'
    /usr/local/sbin/wmp-off $2

elif [ "$1" = "stop" ]; then
    systemctl stop wmp.timer
    systemctl disable wmp.timer
    systemctl daemon-reload

elif [ "$1" = "start" ]; then
    systemctl daemon-reload
    systemctl enable wmp.timer
    systemctl start wmp.timer

elif [ "$1" = "uninstall" ]; then
    echo "Removing WakeMyPotato..."
    systemctl stop wmp.timer
    systemctl disable wmp.timer
    rm -rf /etc/systemd/system/wmp.timer /etc/systemd/system/wmp.service
    rm -rf /usr/local/sbin/wmp /usr/local/sbin/wmp-check /usr/local/sbin/wmp-off
    systemctl daemon-reload
    echo "All clear."

else
    echo "Invalid command. Use 'sudo wmp help' to see available commands." >&2
fi
