#!/bin/bash
# /usr/local/sbin/wmp-check
# This file is part of the WakeMyPotato (WMP) systemd service.
# https://github.com/pablogila/WakeMyPotato
# It will safely power off RAID disks before an emergency shutdown on AC outage.

# The system is automatically restored after the specified waketime or once power is back.
# The argument specifies the wake time for the rtcwake call in seconds.
# Users should not invoke this script directly, but through the wmp command interface.
# For e.g. 600s, the wmp command should call this script as:
# /usr/local/sbin/wmp-check 600
# For e.g. 1000s, checking also the connection to an IP address:
# /usr/local/sbin/wmp-check 1000 192.168.1.1

SECONDS=$1
IP=$2

# New wake up call, without powering off the system.
# This runs first, in case the battery is so low that the rest of the script cannot run!
rtcwake -m no -s "$SECONDS"

# If there is no AC power but the system is still running, let's shut it down safely
if ! upower -i $(upower -e | grep 'line_power') | grep -q 'online:\s*yes'; then
    /usr/local/sbin/wmp-off "$SECONDS"
    exit 0
fi

# If an IP is provided, check that we can ping it, otherwise shut down
if [ -n "$IP" ]; then
    if ! ping -q -c1 "$IP" &> /dev/null; then
        /usr/local/sbin/wmp-off "$SECONDS"
        exit 0
    fi
fi
